### ISSUE TITLE
linux 报错了

### ISSUE THREAD

**Issue by hktalent** [eatmoreapple/openwechat#150]
linux 报错了
```
2022/12/11 08:53:54 扫码成功,请在手机上确认登录
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7efe4676c378]

runtime stack:
runtime.throw({0x7cda8a?, 0x7efe477bddd0?})
        /usr/local/go/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:802 +0x3a9

goroutine 38 [syscall]:
runtime.cgocall(0x696770, 0xc0000b1598)
        /usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc0000b1570 sp=0xc0000b1538 pc=0x4050bc
net._C2func_getaddrinfo(0xc000019580, 0x0, 0xc0004984b0, 0xc00051a048)
        _cgo_gotypes.go:94 +0x56 fp=0xc0000b1598 sp=0xc0000b1570 pc=0x58baf6
net.cgoLookupIPCNAME.func1({0xc000019580, 0x0?, 0x0?}, 0xc000019560?, 0x58fc7b?)
        /usr/local/go/src/net/cgo_unix.go:160 +0x9f fp=0xc0000b15f0 sp=0xc0000b1598 pc=0x58d39f
net.cgoLookupIPCNAME({0x7ba791, 0x3}, {0xc000019560, 0xa})
        /usr/local/go/src/net/cgo_unix.go:160 +0x16d fp=0xc0000b1738 sp=0xc0000b15f0 pc=0x58cc0d
net.cgoIPLookup(0xa31670?, {0x7ba791?, 0xc000019570?}, {0xc000019560?, 0xc00051e160?})
        /usr/local/go/src/net/cgo_unix.go:217 +0x3b fp=0xc0000b17a8 sp=0xc0000b1738 pc=0x58d45b
net.cgoLookupIP.func1()
        /usr/local/go/src/net/cgo_unix.go:227 +0x36 fp=0xc0000b17e0 sp=0xc0000b17a8 pc=0x58d896
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0000b17e8 sp=0xc0000b17e0 pc=0x463e01
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:227 +0x12a

goroutine 1 [select]:
net/http.(*Transport).getConn(0x9f13c0, 0xc000061900, {{}, 0x0, {0xc0001d1320, 0x5}, {0xc000019560, 0xe}, 0x0})
        /usr/local/go/src/net/http/transport.go:1375 +0x5c6
net/http.(*Transport).roundTrip(0x9f13c0, 0xc000174800)
        /usr/local/go/src/net/http/transport.go:581 +0x76f
net/http.(*Transport).RoundTrip(0xc000174800?, 0x8430a0?)
        /usr/local/go/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc000174700, {0x8430a0, 0x9f13c0}, {0x7aeac0?, 0x4a7d01?, 0xa31e40?})
        /usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc000079b30, 0xc000174700, {0x0?, 0xc000121a18?, 0xa31e40?})
        /usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc000079b30, 0xc000174700)
        /usr/local/go/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
github.com/eatmoreapple/openwechat.(*Client).do(0xc00006c2d0, 0xc00052ebc0?)
        /app/vendor/github.com/eatmoreapple/openwechat/client.go:85 +0x8d
github.com/eatmoreapple/openwechat.(*Client).Do(0x75e5a0?, 0x0?)
        /app/vendor/github.com/eatmoreapple/openwechat/client.go:113 +0x1e
github.com/eatmoreapple/openwechat.desktopMode.GetLoginInfo({}, 0xc0001d1320?, {0xc0001d1320?, 0x90?})
        /app/vendor/github.com/eatmoreapple/openwechat/mode.go:66 +0x1dd
github.com/eatmoreapple/openwechat.(*Client).GetLoginInfo(...)
        /app/vendor/github.com/eatmoreapple/openwechat/client.go:153
github.com/eatmoreapple/openwechat.(*Caller).GetLoginInfo(0xc000013e70, {0xc00016e200?, 0x0?, 0x0?})
        /app/vendor/github.com/eatmoreapple/openwechat/caller.go:87 +0xef
github.com/eatmoreapple/openwechat.(*Bot).HandleLogin(0xc000170000, {0xc00016e200?, 0x200?, 0x0?})
        /app/vendor/github.com/eatmoreapple/openwechat/bot.go:180 +0x2e
github.com/eatmoreapple/openwechat.(*Bot).LoginWithUUID(0xc000170000, {0xc000496040, 0xc})
        /app/vendor/github.com/eatmoreapple/openwechat/bot.go:144 +0x185
github.com/eatmoreapple/openwechat.(*Bot).Login(0xc000170000)
        /app/vendor/github.com/eatmoreapple/openwechat/bot.go:124 +0x7b
github.com/eatmoreapple/openwechat.(*Bot).HotLogin(0xc000170000, {0x844450?, 0xc00000e750?}, {0x0, 0x0, 0xc000121f70?})
        /app/vendor/github.com/eatmoreapple/openwechat/bot.go:85 +0xc7
github.com/869413421/wechatbot/bootstrap.Run()
        /app/bootstrap/bootstrap.go:24 +0x10c
main.main()
        /app/main.go:8 +0x17

goroutine 6 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc000013e50, 0x0?)
        /app/vendor/github.com/patrickmn/go-cache/cache.go:1079 +0x85
created by github.com/patrickmn/go-cache.runJanitor
        /app/vendor/github.com/patrickmn/go-cache/cache.go:1099 +0xed

goroutine 20 [IO wait]:
internal/poll.runtime_pollWait(0x7efe4678b098, 0x72)
        /usr/local/go/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00009a080?, 0xc00019a000?, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Read(0xc00009a080, {0xc00019a000, 0x10b7, 0x10b7})
        /usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00009a080, {0xc00019a000?, 0xc00043aae0?, 0xc00019a00d?})
        /usr/local/go/src/net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000010668, {0xc00019a000?, 0x0?, 0x0?})
        /usr/local/go/src/net/net.go:183 +0x45
crypto/tls.(*atLeastReader).Read(0xc000262120, {0xc00019a000?, 0x0?, 0x0?})
        /usr/local/go/src/crypto/tls/conn.go:785 +0x3d
bytes.(*Buffer).ReadFrom(0xc0001653f8, {0x842d20, 0xc000262120})
        /usr/local/go/src/bytes/buffer.go:204 +0x98
crypto/tls.(*Conn).readFromUntil(0xc000165180, {0x843020?, 0xc000010668}, 0xba?)
        /usr/local/go/src/crypto/tls/conn.go:807 +0xe5
crypto/tls.(*Conn).readRecordOrCCS(0xc000165180, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:614 +0x116
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:582
crypto/tls.(*Conn).Read(0xc000165180, {0xc0000ac000, 0x1000, 0x0?})
        /usr/local/go/src/crypto/tls/conn.go:1285 +0x16f
net/http.(*persistConn).Read(0xc0001250e0, {0xc0000ac000?, 0xc0002e2000?, 0xc0004d7d30?})
        /usr/local/go/src/net/http/transport.go:1929 +0x4e
bufio.(*Reader).fill(0xc0000a39e0)
        /usr/local/go/src/bufio/bufio.go:106 +0x103
bufio.(*Reader).Peek(0xc0000a39e0, 0x1)
        /usr/local/go/src/bufio/bufio.go:144 +0x5d
net/http.(*persistConn).readLoop(0xc0001250e0)
        /usr/local/go/src/net/http/transport.go:2093 +0x1ac
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1750 +0x173e

goroutine 21 [select]:
net/http.(*persistConn).writeLoop(0xc0001250e0)
        /usr/local/go/src/net/http/transport.go:2392 +0xf5
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1751 +0x1791

goroutine 36 [select]:
net.(*Resolver).lookupIPAddr(0xa31660, {0x845328?, 0xc0004becc0}, {0x7ba791, 0x3}, {0xc000019560, 0xa})
        /usr/local/go/src/net/lookup.go:325 +0x51b
net.(*Resolver).internetAddrList(0x845328?, {0x845328?, 0xc0004becc0?}, {0x7ba791, 0x3}, {0xc000019560?, 0xe?})
        /usr/local/go/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0xa682f0?, {0x845328, 0xc0004becc0}, {0x7bac14, 0x4}, {0x7ba791?, 0x7efe4d33dfff?}, {0xc000019560, 0xe}, {0x0, ...})
        /usr/local/go/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0xc000062240, {0x845328, 0xc0004becc0}, {0x7ba791, 0x3}, {0xc000019560, 0xe})
        /usr/local/go/src/net/dial.go:406 +0x448
net/http.(*Transport).dial(0x0?, {0x845328?, 0xc0004becc0?}, {0x7ba791?, 0x0?}, {0xc000019560?, 0x0?})
        /usr/local/go/src/net/http/transport.go:1169 +0xda
net/http.(*Transport).dialConn(0x9f13c0, {0x845328, 0xc0004becc0}, {{}, 0x0, {0xc0001d1320, 0x5}, {0xc000019560, 0xe}, 0x0})
        /usr/local/go/src/net/http/transport.go:1607 +0x83f
net/http.(*Transport).dialConnFor(0x0?, 0xc00051e160)
        /usr/local/go/src/net/http/transport.go:1449 +0xb0
created by net/http.(*Transport).queueForDial
        /usr/local/go/src/net/http/transport.go:1418 +0x3d2

goroutine 37 [select]:
net.cgoLookupIP({0x8452b8, 0xc000061980}, {0x7ba791, 0x3}, {0xc000019560, 0xa})
        /usr/local/go/src/net/cgo_unix.go:228 +0x1aa
net.(*Resolver).lookupIP(0xa31660, {0x8452b8, 0xc000061980}, {0x7ba791, 0x3}, {0xc000019560, 0xa})
        /usr/local/go/src/net/lookup_unix.go:96 +0x128
net.glob..func1({0x8452b8?, 0xc000061980?}, 0x0?, {0x7ba791?, 0x0?}, {0xc000019560?, 0x62b170?})
        /usr/local/go/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
        /usr/local/go/src/net/lookup.go:319 +0x9f
internal/singleflight.(*Group).doCall(0xa31670, 0xc00049a410, {0xc000019570, 0xe}, 0xc00051e160?)
        /usr/local/go/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
        /usr/local/go/src/internal/singleflight/singleflight.go:88 +0x2ec
```

**Comment by eatmoreapple** [comment]
go 重新安装一下
