### ISSUE TITLE
超过字数限制,不会自动清除

### ISSUE THREAD

**Issue by liquan1998** [eatmoreapple/openwechat#323]
提问和回复多了,超过字数限制,不会自动清除.出现如下错误 . 每次还要用/cmd clear 清除
另外 ,群聊的时候,不同人的提问,都作为回复的上下文.没有区分不同人的问题.

Error: Request failed with status code 429
at createError (/app/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
at settle (/app/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/app/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
at IncomingMessage.emit (node:events:524:35)
at IncomingMessage.emit (node:domain:489:12)
at endReadableNT (node:internal/streams/readable:1359:12)
at processTicksAndRejections (node:internal/process/task_queues:82:21) {

**Comment by eatmoreapple** [comment]
您串台了
