### ISSUE TITLE
PushLogin报错，是微信接口变化导致的吗？

### ISSUE THREAD

**Issue by CliffHan** [eatmoreapple/openwechat#532]
调用代码基本是照着这段例子写的，只改了文件名和后续的错误处理

```go
bot := openwechat.DefaultBot()
reloadStorage := openwechat.NewFileHotReloadStorage("storage.json")
defer reloadStorage.Close()
err = bot.PushLogin(reloadStorage, openwechat.NewRetryLoginOption())
```

扫码后报错，看起来是写入 json 出错了，得到的 log 如下：
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xa7912b]

goroutine 7 [running]:
encoding/json.(*encodeState).marshal.func1()
        C:/Program Files/Go/src/encoding/json/encode.go:294 +0x6d
panic({0xda3060?, 0x13f47f0?})
        C:/Program Files/Go/src/runtime/panic.go:785 +0x132
encoding/json.appendString[...]({0xc0001d6a90?, 0x12?, 0x7?}, {0x0?, 0xc000079cb4}, 0x1)
        C:/Program Files/Go/src/encoding/json/encode.go:971 +0xab
encoding/json.stringEncoder(0xc000198bc0, {0xd67080?, 0xc0001da860?, 0x0?}, {0x68?, 0x31?})
        C:/Program Files/Go/src/encoding/json/encode.go:590 +0x3c7
encoding/json.structEncoder.encode({{{0xc000261b08, 0xc, 0x10}, 0xc00039e9f0, 0xc00039ea20}}, 0xc000198bc0, {0xe28380?, 0xc0001da840?, 0xc0001d6a2b?}, {0x0, ...})
        C:/Program Files/Go/src/encoding/json/encode.go:715 +0x21e
encoding/json.mapEncoder.encode({0xc0000c1420?}, 0xc000198bc0, {0xd9a760?, 0xc00017b980?, 0x18?}, {0x21?, 0x6a?})
        C:/Program Files/Go/src/encoding/json/encode.go:772 +0x4e6
encoding/json.mapEncoder.encode({0xe4d79f?}, 0xc000198bc0, {0xd9a7c0?, 0xc00017a6d8?, 0x100000000000008?}, {0xa?, 0x0?})
        C:/Program Files/Go/src/encoding/json/encode.go:772 +0x4e6
encoding/json.structEncoder.encode({{{0xc0001f78c8, 0x3, 0x4}, 0xc00039eae0, 0xc00039eb10}}, 0xc000198bc0, {0xdfe040?, 0xc00017a6c0?, 0xc000199780?}, {0x0, ...})
        C:/Program Files/Go/src/encoding/json/encode.go:715 +0x21e
encoding/json.ptrEncoder.encode({0x787f68?}, 0xc000198bc0, {0xd92de0?, 0xc000199780?, 0xc000195910?}, {0x6?, 0x0?})
        C:/Program Files/Go/src/encoding/json/encode.go:887 +0x223
encoding/json.structEncoder.encode({{{0xc0003ba488, 0x6, 0x8}, 0xc00039ec90, 0xc00039ecc0}}, 0xc000198bc0, {0xe10c40?, 0xc000199780?, 0x788117?}, {0x0, ...})
        C:/Program Files/Go/src/encoding/json/encode.go:715 +0x21e
encoding/json.(*encodeState).reflectValue(0xc000198bc0, {0xe10c40?, 0xc000199780?, 0xc000080008?}, {0xa0?, 0x40?})
        C:/Program Files/Go/src/encoding/json/encode.go:322 +0x73
encoding/json.(*encodeState).marshal(0x7353d3?, {0xe10c40?, 0xc000199780?}, {0xe5?, 0x43?})
        C:/Program Files/Go/src/encoding/json/encode.go:298 +0xbd
encoding/json.(*Encoder).Encode(0xc0000c1b20, {0xe10c40, 0xc000199780})
        C:/Program Files/Go/src/encoding/json/stream.go:210 +0xd0
github.com/eatmoreapple/openwechat.JsonSerializer.Encode(...)
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/serializer.go:19
github.com/eatmoreapple/openwechat.(*Bot).DumpTo(0xc00015a1c0, {0x223f72cd498, 0xc000067600})
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot.go:321 +0x11b
github.com/eatmoreapple/openwechat.(*Bot).DumpHotReloadStorage(...)
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot.go:306
github.com/eatmoreapple/openwechat.(*Bot).webInit(0xc00015a1c0)
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot.go:161 +0x33e
github.com/eatmoreapple/openwechat.(*Bot).loginFromURL(0xc00015a1c0, 0xb8?)
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot.go:137 +0x15c
github.com/eatmoreapple/openwechat.(*LoginChecker).CheckLogin(0xc0000c1d68)
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot_login.go:274 +0x1fb
github.com/eatmoreapple/openwechat.(*ScanLogin).checkLogin(0x223d1ffac48?, 0xfb7328?, {0xc0001a8d94?, 0x223d1ff0108?})
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot_login.go:185 +0x91
github.com/eatmoreapple/openwechat.(*ScanLogin).Login(0xc00002f4c0?, 0xc00015a1c0?)
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot_login.go:172 +0x58
github.com/eatmoreapple/openwechat.(*Bot).login(0xc00015a1c0, {0xfb24a0, 0xc00002f4c0})
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot.go:63 +0xab
github.com/eatmoreapple/openwechat.(*Bot).Login(...)
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot.go:75
github.com/eatmoreapple/openwechat.(*RetryLoginOption).OnError(0xd1b109?, 0xc00015a1c0, {0xfb1360?, 0x13f5360?})
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot_login.go:107 +0x85
github.com/eatmoreapple/openwechat.BotOptionGroup.OnError({0xc00002f4a0?, 0xc00015a1c0?, 0xc00002f4b0?}, 0xc00015a1c0, {0xfb1360, 0x13f5360})
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot_login.go:61 +0x70
github.com/eatmoreapple/openwechat.(*Bot).login(0xc00015a1c0, {0xfb16a0, 0xc00002f4b0})
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot.go:64 +0xcf
github.com/eatmoreapple/openwechat.(*Bot).PushLogin(...)
        C:/Users/cliff/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.7/bot.go:95
```

go语言我这边还是初学者，猜测应该是 HotReloadStorageItem struct 的某个成员为空导致的问题？

**Comment by CliffHan** [comment]
顺便说一句，stroage.go 的文件名有错，应为 storage.go

**Comment by CliffHan** [comment]
似乎是我没有善用搜索的问题
https://github.com/eatmoreapple/openwechat/issues/523

**Comment by eatmoreapple** [comment]
> 顺便说一句，stroage.go 的文件名有错，应为 storage.go

哈哈
