### ISSUE TITLE
msg.SenderInGroup() 频繁报错导致程序退出运行

### ISSUE THREAD

**Issue by wordgao** [eatmoreapple/openwechat#548]
`
//获取消息在群里面的发送者
senderFrom, _ := msg.SenderInGroup()

//TODO senderFrom.NickName 程序几乎运行不定时的出现程序恐慌，导致程序退出运行。
nike:= fmt.Sprintf("%s\n", senderFrom.NickName)
fmt.Println(nike)

`

## 错误代码
`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xf8 pc=0x8b1ce8]

goroutine 120 [running]:
main.start.func1(0xc00064c008)
        /home/nisa/go/src/softlist/openwx/main.go:131 +0x428
github.com/eatmoreapple/openwechat.(*Bot).syncCheck(0xc00035a0e0)
        /home/nisa/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.8/bot.go:245 +0x271
github.com/eatmoreapple/openwechat.(*Bot).webInit.func1()
        /home/nisa/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.8/bot.go:186 +0x8c
created by github.com/eatmoreapple/openwechat.(*Bot).webInit in goroutine 1
        /home/nisa/go/pkg/mod/github.com/eatmoreapple/openwechat@v1.4.8/bot.go:178 +0x326

Process finished with the exit code 2

`

**Comment by eatmoreapple** [comment]
要处理 error，error 不等于 nil 的时候，sender 是 nil
